In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('Films2.csv')

In [3]:
df.shape

(40524, 12)

In [4]:
df.describe()

         Unnamed: 0      Released        Rating  Movie_runtime     Metascore
count  40524.000000  40517.000000  38203.000000   38021.000000  12574.000000
mean   23452.044393   2014.229262      5.985399     103.305384     55.933752
std    14480.130257      9.257136      1.352948      23.185477     17.320990
min        0.000000   1972.000000      1.000000       1.000000      1.000000
25%    10366.750000   2010.000000      5.200000      90.000000     44.000000
50%    23310.500000   2017.000000      6.100000      99.000000     57.000000
75%    36876.250000   2021.000000      6.900000     114.000000     69.000000
max    47499.000000   2023.000000     10.000000     808.000000    100.000000

In [5]:
df.isnull().sum()

Unnamed: 0            0
Movie                 0
Released              7
Rating             2321
Movie_runtime      2503
Certified         24403
Genre               314
Metascore         27950
Movie_director      248
Stars               457
Description           0
Image                 0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40524 entries, 0 to 40523
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      40524 non-null  int64
 1   Movie           40524 non-null  object
 2   Released        40517 non-null  float64
 3   Rating          38203 non-null  float64
 4   Movie_runtime   38021 non-null  float64
 5   Certified       16121 non-null  object
 6   Genre           40210 non-null  object
 7   Metascore       12574 non-null  float64
 8   Movie_director  40276 non-null  object
 9   Stars           40067 non-null  object
 10  Description     40524 non-null  object
 11  Image           40524 non-null  object
dtypes: float64(4), int64(1), object(7)
memory usage: 3.7+ MB

In [7]:
df.columns

Index(['Unnamed: 0', 'Movie', 'Released', 'Rating', 'Movie_runtime',
       'Certified', 'Genre', 'Metascore', 'Movie_director', 'Stars',
       'Description', 'Image'],
      dtype='object')

In [8]:
df = df.drop(columns = ['Unnamed: 0'])
df

,Movie,Released,Rating,Movie_runtime,Certified,Genre,Metascore,Movie_director,Stars,Description,Image
0,The Shawshank Redemption,1994.0,9.3,142.0,A,Drama,82.0,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...","Over the course of several years, two convicts...",https://m.media-amazon.com/images/M/MV5BNDE3OD...
1,The Dark Knight,2008.0,9.0,152.0,UA,"Action, Crime, Drama",84.0,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker wreaks havo...,https://m.media-amazon.com/images/M/MV5BMTMxNT...
2,Inception,2010.0,8.8,148.0,UA,"Action, Adventure, Sci-Fi",74.0,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellio...",A thief who steals corporate secrets through t...,https://m.media-amazon.com/images/M/MV5BMjAxMz...
3,Fight Club,1999.0,8.8,139.0,A,Drama,67.0,David Fincher,"Brad Pitt, Edward Norton, Meat Loaf, Zach Grenier",An insomniac office worker and a devil-may-car...,https://m.media-amazon.com/images/M/MV5BNDIzND...
4,Forrest Gump,1994.0,8.8,142.0,UA,"Drama, Romance",82.0,Robert Zemeckis,"Tom Hanks, Robin Wright, Gary Sinise, Sally Field",The history of the United States from the 1950...,https://m.media-amazon.com/images/M/MV5BNWIwOD...
...,...,...,...,...,...,...,...,...,...,...,...
40519,Before You Die,2022.0,8.3,NaN,U,Drama,NaN,Suvendu Raj Ghosh,"Kavya Kashyap, Mushtaq Khan, Mukesh Rishi, Pun...","'Before You Die...', a film based on how a can...",https://m.media-amazon.com/images/M/MV5BZjlmYj...
40520,Tina & Bettina 2: The Comeback,2023.0,5.0,90.0,NaN,Comedy,NaN,Jonas Lien Svarstad,"Tshawe Baqwa, Kim Fairchild, Henrik Fladseth, ...",10 long years have passed. Things are not so g...,https://m.media-amazon.com/images/M/MV5BNDliZT...
40521,Woman in the Chair,2022.0,5.1,NaN,NaN,Horror,NaN,Derek Hammer,"Cynthia Cheston, Mark Chinnery, Evan De Sousa,...",A man finds a ghost sitting in a chair that ne...,https://m.media-amazon.com/images/M/MV5BNWVhNj...
40522,Chrzciny,2022.0,5.9,88.0,NaN,Drama,NaN,Jakub Skoczen,"Katarzyna Figura, Maciej Musialowski, Tomasz S...","December, 1981. Marianna, a zealous Catholic, ...",https://m.media-amazon.com/images/M/MV5BNWY2YW...
40523,Barren,2022.0,8.0,108.0,NaN,Drama,NaN,Mordechai Vardi,"Mili Eshet, Yoav Rotman, Ilanit Ben-Yaakov, Ne...",A childless young ultra-orthodox couple faces ...,https://m.media-amazon.com/images/M/MV5BNjJjND...

In [9]:
df['Certified'].unique()

array(['A', 'UA', 'U', 'R', '15+', '18', '13', '12+', '16', '(Banned)',
       'PG', 'PG-13', nan, 'U/A', '7', 'All', 'Not', '12', 'Unrated',
       '18+', 'G', 'NC-17', '16+', '7+', 'GP', '13+'], dtype=object)

In [10]:
df['Certified']=df['Certified'].map({'R':'R', '15+':'U/A', '18':'A', '13':'U/A', '12+':'U/A', '16':'A',
       'PG':'U', 'PG-13':'U/A','UA':'U/A', '7':'U', 'All':'U', 'Not':'A', '12':'U/A','(Banned)':'Ban','Unrated':'U/A',
       '18+':'A', 'G':'U', 'NC-17':'A', '16+':'A', '7+':'U', 'GP':'U'})

In [11]:
df['Certified'].unique()

array([nan, 'U/A', 'R', 'A', 'Ban', 'U'], dtype=object)

In [12]:
df['Certified'] =df['Certified'].fillna('U/A')

In [13]:
df['Certified'].unique()

array(['U/A', 'R', 'A', 'Ban', 'U'], dtype=object)

In [14]:
df.tail()

,Movie,Released,Rating,Movie_runtime,Certified,Genre,Metascore,Movie_director,Stars,Description,Image
40519,Before You Die,2022.0,8.3,NaN,U/A,Drama,NaN,Suvendu Raj Ghosh,"Kavya Kashyap, Mushtaq Khan, Mukesh Rishi, Pun...","'Before You Die...', a film based on how a can...",https://m.media-amazon.com/images/M/MV5BZjlmYj...
40520,Tina & Bettina 2: The Comeback,2023.0,5.0,90.0,U/A,Comedy,NaN,Jonas Lien Svarstad,"Tshawe Baqwa, Kim Fairchild, Henrik Fladseth, ...",10 long years have passed. Things are not so g...,https://m.media-amazon.com/images/M/MV5BNDliZT...
40521,Woman in the Chair,2022.0,5.1,NaN,U/A,Horror,NaN,Derek Hammer,"Cynthia Cheston, Mark Chinnery, Evan De Sousa,...",A man finds a ghost sitting in a chair that ne...,https://m.media-amazon.com/images/M/MV5BNWVhNj...
40522,Chrzciny,2022.0,5.9,88.0,U/A,Drama,NaN,Jakub Skoczen,"Katarzyna Figura, Maciej Musialowski, Tomasz S...","December, 1981. Marianna, a zealous Catholic, ...",https://m.media-amazon.com/images/M/MV5BNWY2YW...
40523,Barren,2022.0,8.0,108.0,U/A,Drama,NaN,Mordechai Vardi,"Mili Eshet, Yoav Rotman, Ilanit Ben-Yaakov, Ne...",A childless young ultra-orthodox couple faces ...,https://m.media-amazon.com/images/M/MV5BNjJjND...

In [15]:
df.rename(columns={'Movie':'Title','Released':'Year_of_Release'},inplace = True)

In [16]:
df.describe()

       Year_of_Release        Rating  Movie_runtime     Metascore
count     40517.000000  38203.000000   38021.000000  12574.000000
mean       2014.229262      5.985399     103.305384     55.933752
std           9.257136      1.352948      23.185477     17.320990
min        1972.000000      1.000000       1.000000      1.000000
25%        2010.000000      5.200000      90.000000     44.000000
50%        2017.000000      6.100000      99.000000     57.000000
75%        2021.000000      6.900000     114.000000     69.000000
max        2023.000000     10.000000     808.000000    100.000000

In [17]:
df['Metascore'].mode()

0    65.0
Name: Metascore, dtype: float64

In [18]:
df[df['Rating']>5]['Rating'].unique()

array([ 9.3,  9. ,  8.8,  8.9,  8.7,  9.2,  8.4,  8.6,  8.5,  8.2,  8.3,
        8. ,  7.9,  8.1,  7.2,  7.8,  7.3,  7. ,  7.1,  6.9,  7.4,  7.7,
        7.6,  6.5,  7.5,  6.6,  6.4,  6.8,  5.9,  6.3,  6.7,  6.2,  5.3,
        6.1,  5.8,  5.7,  5.6,  5.5,  6. ,  5.4,  5.1,  5.2,  9.1,  9.9,
        9.6,  9.7,  9.4,  9.8, 10. ,  9.5])

In [19]:
df[df['Rating']<5]['Rating'].unique()

array([4.2, 4.8, 3.8, 4.9, 1.9, 4.3, 4. , 4.6, 3.4, 3.1, 2.8, 2.4, 1.2,
       4.7, 3.3, 3.6, 4.5, 3.9, 4.4, 2.5, 3.5, 1. , 4.1, 2.7, 2.2, 2. ,
       3.7, 2.6, 3. , 1.6, 1.5, 2.1, 3.2, 2.9, 1.7, 1.3, 1.8, 1.4, 2.3,
       1.1])

In [20]:
rate_9 = df[df['Rating']==9]['Metascore'].mode()[1]
rate_8 = df[df['Rating']==8]['Metascore'].mode()[1]
rate_7 = df[df['Rating']==7]['Metascore'].mode()[0]
rate_6 = df[df['Rating']==6]['Metascore'].mode()[1]
rate_5 = df[df['Rating']==5]['Metascore'].mode()[1]
rate_4 = df[df['Rating']==4]['Metascore'].mode()[1]
print(rate_9,rate_8,rate_7,rate_6,rate_5,rate_4)

84.0 78.0 72.0 57.0 35.0 22.0

In [21]:
self_employed_dict = {1.9:14, 1.2:14, 1.0:14 , 1.6:14, 1.5:14, 1.7:14, 1.3:14, 1.8:14, 1.4:14, 1.1:14,9.3:82,  9.2:82,  9.5:82,  9.4:82,  9.8:82,  9.7:82,  9.1:82,  9.6:82, 10.0:82 ,  9.9:82, 4.2:27, 4.8:27, 3.8:27, 4.9:27, 4.3:27, 4.0:27 , 4.6:27, 3.4:27, 3.1:27, 2.8:27, 2.4:27,4.7:27, 3.3:27, 3.6:27, 4.5:27, 3.9:27, 4.4:27, 2.5:27, 3.5:27,4.1:27, 2.7:27, 2.2:27, 2.0:27 ,
       3.7:27, 2.6:27, 3.0:27, 2.1:27, 3.2:27, 2.9:27, 2.3:27, 8.4:78,  8.6:85,  8.5:85,  8.2:78,  8.3:78,
        8.0:78 ,  7.9:78,  8.1:78,  7.2:65,  7.8:65,  7.3:65,  7.0:65 ,  7.1:65,  6.9:65,  7.4:65,  7.7:78,
        7.6:65,  6.5:54,  7.5:65,  6.6:65,  6.4:49,  6.8:65,  5.9:49,  6.3:54,  6.7:65,  6.2:54,  5.3:49,
        6.1:54,  5.8:49,  5.7:49,  5.6:49,  5.5:49,  6.0:54 ,  5.4:49,  5.1:49,  5.2:49,  8.8:83,  8.9:84,  8.7:85,5.0:49,9.0:84 }
df['Metascore'] = df['Metascore'].fillna(df['Rating'].map(self_employed_dict))

In [22]:
df[df['Metascore'].isnull()]

,Title,Year_of_Release,Rating,Movie_runtime,Certified,Genre,Metascore,Movie_director,Stars,Description,Image
10995,Tales of the City,2021.0,NaN,NaN,U/A,Musical,NaN,Jason Moore,"Mary Birdsong, Josh Breckenridge, Manoel Felci...",One of the highest-selling productions in A.C....,https://m.media-amazon.com/images/M/MV5BNWY3Ym...
11015,Possessed Love,2021.0,NaN,NaN,U/A,"Drama, Horror, Romance",NaN,Manmeet Singh Sodhi,"Surbhi Shukla, Sachin Sharma, Unika Ray, Harsh...",Everything was going well for the bride but he...,https://m.media-amazon.com/images/M/MV5BZDdiNT...
11043,Sakshi,2021.0,NaN,112.0,U/A,Thriller,NaN,Ajay Ram,"Madhumita Biswas, Yugansh Juneja, Vikram Masta...",Virat and Prachi are engaged to be married. Bu...,https://m.media-amazon.com/images/M/MV5BY2ZiYm...
11090,Pain Killer,2021.0,NaN,NaN,U/A,Action,NaN,Vs Phanindra,NaN,Add a Plot,https://m.media-amazon.com/images/M/MV5BMGYzY2...
11138,The Hellenback's Alex in Wonderland,2021.0,NaN,90.0,U/A,Drama,NaN,Jimmie Romero,"Chelsea Gilson, Jimmie Romero, Mara Ohara, Jef...",Alex leaves home to pursue her acting career i...,https://m.media-amazon.com/images/M/MV5BNjcwOG...
...,...,...,...,...,...,...,...,...,...,...,...
40493,Status,2023.0,NaN,62.0,U/A,"Crime, Drama",NaN,Vitaliy Belyan,"Marina Bayda, Timur Gatiyatullin, Bogdan Novik...","A young man from the provinces, in search of a...",https://m.media-amazon.com/images/M/MV5BNzkzYz...
40501,Oliva,2023.0,NaN,NaN,U/A,Comedy,NaN,Luciano Leyrado,"Juan Leyrado, Andrea Frigerio, Ignacio Toselli...",Add a Plot,https://m.media-amazon.com/images/M/MV5BZWUzMT...
40506,Spellbound,2023.0,NaN,NaN,U/A,Comedy,NaN,Alex Ross,"Kathryn Hollis Peters, Lincoln Brown, Chelsea ...",One night at a strip club Johnny disrespects a...,https://m.media-amazon.com/images/M/MV5BMjU2ZD...
40509,A Song from the Dark,2023.0,NaN,105.0,U/A,"Fantasy, Horror",NaN,Ogodinife Okpue,"Wale Ojo, Dean Kilbey, Vanessa Vanderpuye, Kan...","After the mysterious death of her husband, a w...",https://m.media-amazon.com/images/M/MV5BYjcwMG...
40512,Ready Cash,2023.0,NaN,29.0,U/A,"Crime, Drama, Horror",NaN,"Austin Shell, Dylan M Shell","Timothy J. Cox, James Dickey, Zach Meiser, Dan...","After a drug-fueled bender, Justin realizes th...",https://m.media-amazon.com/images/S/sash/NapCx...

In [23]:
df =df.dropna(subset = ['Rating','Genre','Stars','Movie_director','Year_of_Release'])
df

,Title,Year_of_Release,Rating,Movie_runtime,Certified,Genre,Metascore,Movie_director,Stars,Description,Image
0,The Shawshank Redemption,1994.0,9.3,142.0,U/A,Drama,82.0,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...","Over the course of several years, two convicts...",https://m.media-amazon.com/images/M/MV5BNDE3OD...
1,The Dark Knight,2008.0,9.0,152.0,U/A,"Action, Crime, Drama",84.0,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker wreaks havo...,https://m.media-amazon.com/images/M/MV5BMTMxNT...
2,Inception,2010.0,8.8,148.0,U/A,"Action, Adventure, Sci-Fi",74.0,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellio...",A thief who steals corporate secrets through t...,https://m.media-amazon.com/images/M/MV5BMjAxMz...
3,Fight Club,1999.0,8.8,139.0,U/A,Drama,67.0,David Fincher,"Brad Pitt, Edward Norton, Meat Loaf, Zach Grenier",An insomniac office worker and a devil-may-car...,https://m.media-amazon.com/images/M/MV5BNDIzND...
4,Forrest Gump,1994.0,8.8,142.0,U/A,"Drama, Romance",82.0,Robert Zemeckis,"Tom Hanks, Robin Wright, Gary Sinise, Sally Field",The history of the United States from the 1950...,https://m.media-amazon.com/images/M/MV5BNWIwOD...
...,...,...,...,...,...,...,...,...,...,...,...
40519,Before You Die,2022.0,8.3,NaN,U/A,Drama,78.0,Suvendu Raj Ghosh,"Kavya Kashyap, Mushtaq Khan, Mukesh Rishi, Pun...","'Before You Die...', a film based on how a can...",https://m.media-amazon.com/images/M/MV5BZjlmYj...
40520,Tina & Bettina 2: The Comeback,2023.0,5.0,90.0,U/A,Comedy,49.0,Jonas Lien Svarstad,"Tshawe Baqwa, Kim Fairchild, Henrik Fladseth, ...",10 long years have passed. Things are not so g...,https://m.media-amazon.com/images/M/MV5BNDliZT...
40521,Woman in the Chair,2022.0,5.1,NaN,U/A,Horror,49.0,Derek Hammer,"Cynthia Cheston, Mark Chinnery, Evan De Sousa,...",A man finds a ghost sitting in a chair that ne...,https://m.media-amazon.com/images/M/MV5BNWVhNj...
40522,Chrzciny,2022.0,5.9,88.0,U/A,Drama,49.0,Jakub Skoczen,"Katarzyna Figura, Maciej Musialowski, Tomasz S...","December, 1981. Marianna, a zealous Catholic, ...",https://m.media-amazon.com/images/M/MV5BNWY2YW...
40523,Barren,2022.0,8.0,108.0,U/A,Drama,78.0,Mordechai Vardi,"Mili Eshet, Yoav Rotman, Ilanit Ben-Yaakov, Ne...",A childless young ultra-orthodox couple faces ...,https://m.media-amazon.com/images/M/MV5BNjJjND...

In [24]:
df.isnull().sum()

Title                 0
Year_of_Release       0
Rating                0
Movie_runtime      1278
Certified             0
Genre                 0
Metascore             0
Movie_director        0
Stars                 0
Description           0
Image                 0
dtype: int64

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 37764 entries, 0 to 40523
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Title            37764 non-null  object
 1   Year_of_Release  37764 non-null  float64
 2   Rating           37764 non-null  float64
 3   Movie_runtime    36486 non-null  float64
 4   Certified        37764 non-null  object
 5   Genre            37764 non-null  object
 6   Metascore        37764 non-null  float64
 7   Movie_director   37764 non-null  object
 8   Stars            37764 non-null  object
 9   Description      37764 non-null  object
 10  Image            37764 non-null  object
dtypes: float64(4), object(7)
memory usage: 3.5+ MB

In [26]:
df = df.reset_index()
df.tail(5)

,index,Title,Year_of_Release,Rating,Movie_runtime,Certified,Genre,Metascore,Movie_director,Stars,Description,Image
37759,40519,Before You Die,2022.0,8.3,NaN,U/A,Drama,78.0,Suvendu Raj Ghosh,"Kavya Kashyap, Mushtaq Khan, Mukesh Rishi, Pun...","'Before You Die...', a film based on how a can...",https://m.media-amazon.com/images/M/MV5BZjlmYj...
37760,40520,Tina & Bettina 2: The Comeback,2023.0,5.0,90.0,U/A,Comedy,49.0,Jonas Lien Svarstad,"Tshawe Baqwa, Kim Fairchild, Henrik Fladseth, ...",10 long years have passed. Things are not so g...,https://m.media-amazon.com/images/M/MV5BNDliZT...
37761,40521,Woman in the Chair,2022.0,5.1,NaN,U/A,Horror,49.0,Derek Hammer,"Cynthia Cheston, Mark Chinnery, Evan De Sousa,...",A man finds a ghost sitting in a chair that ne...,https://m.media-amazon.com/images/M/MV5BNWVhNj...
37762,40522,Chrzciny,2022.0,5.9,88.0,U/A,Drama,49.0,Jakub Skoczen,"Katarzyna Figura, Maciej Musialowski, Tomasz S...","December, 1981. Marianna, a zealous Catholic, ...",https://m.media-amazon.com/images/M/MV5BNWY2YW...
37763,40523,Barren,2022.0,8.0,108.0,U/A,Drama,78.0,Mordechai Vardi,"Mili Eshet, Yoav Rotman, Ilanit Ben-Yaakov, Ne...",A childless young ultra-orthodox couple faces ...,https://m.media-amazon.com/images/M/MV5BNjJjND...

In [27]:
df = df.drop(columns = ['index'])
df.tail(4)

,Title,Year_of_Release,Rating,Movie_runtime,Certified,Genre,Metascore,Movie_director,Stars,Description,Image
37760,Tina & Bettina 2: The Comeback,2023.0,5.0,90.0,U/A,Comedy,49.0,Jonas Lien Svarstad,"Tshawe Baqwa, Kim Fairchild, Henrik Fladseth, ...",10 long years have passed. Things are not so g...,https://m.media-amazon.com/images/M/MV5BNDliZT...
37761,Woman in the Chair,2022.0,5.1,NaN,U/A,Horror,49.0,Derek Hammer,"Cynthia Cheston, Mark Chinnery, Evan De Sousa,...",A man finds a ghost sitting in a chair that ne...,https://m.media-amazon.com/images/M/MV5BNWVhNj...
37762,Chrzciny,2022.0,5.9,88.0,U/A,Drama,49.0,Jakub Skoczen,"Katarzyna Figura, Maciej Musialowski, Tomasz S...","December, 1981. Marianna, a zealous Catholic, ...",https://m.media-amazon.com/images/M/MV5BNWY2YW...
37763,Barren,2022.0,8.0,108.0,U/A,Drama,78.0,Mordechai Vardi,"Mili Eshet, Yoav Rotman, Ilanit Ben-Yaakov, Ne...",A childless young ultra-orthodox couple faces ...,https://m.media-amazon.com/images/M/MV5BNjJjND...

In [28]:
df.stack()[0]

Title                                       The Shawshank Redemption
Year_of_Release                                               1994.0
Rating                                                           9.3
Movie_runtime                                                  142.0
Certified                                                        U/A
Genre                                                          Drama
Metascore                                                       82.0
Movie_director                                        Frank Darabont
Stars              Tim Robbins, Morgan Freeman, Bob Gunton, Willi...
Description        Over the course of several years, two convicts...
Image              https://m.media-amazon.com/images/M/MV5BNDE3OD...
dtype: object